### ISSUE TITLE
Crash after linking minecarts

### ISSUE THREAD

**Issue by Jummit** [CammiesCorner/Cammies-Minecart-Tweaks#28]
The game crashed after linking together three minecarts.

Error message:
```
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1688.method_18798()" because "minecart" is null
Exit Code: 255
```

latest.log:

```
[10:50:20] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:911) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1688.method_18798()" because "minecart" is null
	at dev.cammiescorner.cammiesminecarttweaks.utils.MinecartHelper.shouldSlowDown(MinecartHelper.java:20) ~[cammies-minecart-tweaks-1.4.jar:?]
	at net.minecraft.class_1696.mdb99446$lambda$minecarttweaks$slowDown$0$0(class_1696.java:1117) ~[client-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_1696.handler$bca000$minecarttweaks$slowDown(class_1696.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_1696.method_7513(class_1696.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_1688.method_5773(class_1688.java:346) ~[client-intermediary.jar:?]
	at net.minecraft.class_1696.method_5773(class_1696.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:702) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:485) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907) ~[client-intermediary.jar:?]
	... 5 more
```

**Comment by UpcraftLP** [comment]
Already fixed, update the mod.
