### ISSUE TITLE
Crash when placing furnace minecart

### ISSUE THREAD

**Issue by epicfishgamer** [CammiesCorner/Cammies-Minecart-Tweaks#8]
Description: Ticking entity

java.lang.NoSuchFieldError: field_15463
	at dev.cammiescorner.cammiesminecarttweaks.utils.MinecartHelper.shouldSlowDown(MinecartHelper.java:37)
	at net.minecraft.class_1696.handler$cni000$minecarttweaks$slowDown(class_1696.java:1106)
	at net.minecraft.class_1696.method_7513(class_1696.java:108)
	at net.minecraft.class_1688.method_5773(class_1688.java:346)
	at net.minecraft.class_1696.method_5773(class_1696.java:56)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.cammiescorner.cammiesminecarttweaks.utils.MinecartHelper.shouldSlowDown(MinecartHelper.java:37)
	at net.minecraft.class_1696.handler$cni000$minecarttweaks$slowDown(class_1696.java:1106)
	at net.minecraft.class_1696.method_7513(class_1696.java:108)
	at net.minecraft.class_1688.method_5773(class_1688.java:346)
	at net.minecraft.class_1696.method_5773(class_1696.java:56)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: minecraft:furnace_minecart (net.minecraft.class_1696)
	Entity ID: 458
	Entity Name: Minecart with Furnace
	Entity's Exact location: 6246.50, 66.06, -2400.50
	Entity's Block location: World: (6246,66,-2401), Section: (at 6,2,15 in 390,4,-151; chunk contains blocks 6240,-64,-2416 to 6255,319,-2401), Region: (12,-5; contains chunks 384,-160 to 415,-129, blocks 6144,-64,-2560 to 6655,319,-2049)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CammiePone** [comment]
What version of Minecraft and of CMT are you using?

**Comment by epicfishgamer** [comment]
1.18.1 and CMT is 1.4

**Comment by CammiePone** [comment]
That's why. 1.4 isn't compatible with 1.18.1 due to tag changes. That's why it's not marked as 1.18.1 compatible on CF.

**Comment by epicfishgamer** [comment]
Oh my bad! Thanks anyways :)
