### ISSUE TITLE
Game crash when connecting minecarts with chains in some cases

### ISSUE THREAD

**Issue by 9dash** [CammiesCorner/Cammies-Minecart-Tweaks#9]
when connecting a three minecarts in a row with the first minecart being a furnace minecart, the game crashes.

[](https://www.youtube.com/watch?v=WrHWj3lYqOk)

**Comment by CammiePone** [comment]
What version of the mod are you on, what version of MC are you running, Fabric API version, etc

**Comment by 9dash** [comment]
> 
i'm on the latest version of the mod, playing on 1.18.2, fabric api is updated to 0.47.10, and these are all the mods i'm running:
![image](https://user-images.githubusercontent.com/101616948/158361769-52b58038-0253-437c-b034-3c6668309403.png)

and this is the report that minecraft gave after the game crashed:
![image](https://user-images.githubusercontent.com/101616948/158361842-b23c6571-bae3-4cc2-9a77-eb21cbfb7206.png)

**Comment by CammiePone** [comment]
Can you send the full crash report? Need to see which call that is.

**Comment by 9dash** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/15/22, 5:02 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1688.method_18798()" because "minecart" is null
	at dev.cammiescorner.cammiesminecarttweaks.utils.MinecartHelper.shouldSlowDown(MinecartHelper.java:20)
	at net.minecraft.class_1696.mdb8c9a4$lambda$minecarttweaks$slowDown$0$0(class_1696.java:1117)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_1696.handler$zom000$minecarttweaks$slowDown(class_1696.java:1117)
	at net.minecraft.class_1696.method_7513(class_1696.java:108)
	at net.minecraft.class_1688.method_5773(class_1688.java:346)
	at net.minecraft.class_1696.method_5773(class_1696.java:56)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.cammiescorner.cammiesminecarttweaks.utils.MinecartHelper.shouldSlowDown(MinecartHelper.java:20)
	at net.minecraft.class_1696.mdb8c9a4$lambda$minecarttweaks$slowDown$0$0(class_1696.java:1117)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_1696.handler$zom000$minecarttweaks$slowDown(class_1696.java:1117)
	at net.minecraft.class_1696.method_7513(class_1696.java:108)
	at net.minecraft.class_1688.method_5773(class_1688.java:346)
	at net.minecraft.class_1696.method_5773(class_1696.java:56)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:furnace_minecart (net.minecraft.class_1696)
	Entity ID: 1562
	Entity Name: Minecart with Furnace
	Entity's Exact location: -63.50, 64.06, 87.50
	Entity's Block location: World: (-64,64,87), Section: (at 0,0,7 in -4,4,5; chunk contains blocks -64,-64,80 to -49,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['9dash'/159, l='ServerLevel[stuff and things]', x=-61.26, y=63.00, z=84.65]]
	Chunk stats: 3716
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,109,0), Section: (at 0,13,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 830 game time, 830 day time
	Level name: stuff and things
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 103415 (now: false), thunder time: 88811 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 784400200 bytes (748 MiB) / 2919235584 bytes (2784 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 35784.69
	Virtual memory used (MB): 21721.74
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 1585.48
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		fabric: Fabric API 0.47.10+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.7+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		fireworkfrenzy: Firework Frenzy 1.9
		hookshot: Hookshot 25.0
		icarus: Icarus 1.10
		iris: Iris 1.2.2-build.32
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		logical_zoom: Logical Zoom 0.0.14
		minecarttweaks: Cammie's Minecart Tweaks 1.4
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.1.0
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		pride: Pride Lib 1.1.0+1.17
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.0+1.17
		trinkets: Trinkets 3.3.0
		voicechat: Simple Voice Chat 1.18.2-2.2.26
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['9dash'/159, l='ServerLevel[stuff and things]', x=-61.26, y=63.00, z=84.65]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by CammiePone** [comment]
Okay so the spot i thought it was. Good news is I already have it fixed in dev
